name: Home Automation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 4" # Runs at 6pm on Thursdays

permissions: {}

jobs:
  move-vacuum:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Move Vacuum
        env:
          ROBOROCK_USERNAME: ${{ secrets.ROBOROCK_USERNAME }}
          ROBOROCK_USER_DATA: ${{ secrets.ROBOROCK_USER_DATA }}
        run: |
          python command.py app_goto_target "${{ secrets.target_x }}" "${{ secrets.target_y }}" &&
          echo "::notice::Vacuum has been moved to the target location for emptying." ||
          echo "::error::Failed to move the vacuum. Please check the logs for details."
        shell: bash
