name: Move Vacuum for Emptying
on:
  schedule:
    - cron: "0 18 * * 2" # Runs at 6pm on Tuesdays
  workflow_dispatch:

jobs:
  move-vacuum:
    runs-on:
      - self-hosted
      - home

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Move Vacuum
        env:
          ROBOROCK_USER_DATA_FILE: /home/dommas/.roborock_user_data
        run: |
            python goto.py "${{ secrets.target_x }}" "${{ secrets.target_y }}"
