name: Move Vacuum for Emptying
on:
  schedule:
    - cron: "0 18 * * 4" # Runs at 6pm on Thursdays
  workflow_dispatch:

jobs:
  move-vacuum:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Move Vacuum
        env:
          ROBOROCK_USER_DATA: ${{ secrets.ROBOROCK_USER_DATA }}
        run: |
            python goto.py "${{ secrets.target_x }}" "${{ secrets.target_y }}"
