name: "Request Authorization Code"

on:
  workflow_dispatch:

jobs:
  request-code:
    runs-on:
      - self-hosted
      - home

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: apt install -y pipenv && pipenv install

      - name: Run request_code.py
        run: python request_code.py "${{ secrets.username }}"
        shell: bash
